<?php

/**
 * Implement hook_menu
 */
function comments_ajax_menu() {
  $items = array();
  $items['comments/get/%/%'] = array(
    'title' => 'Load comments',
    'page callback' => 'comments_ajax_load',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

function comments_ajax_load($nid, $cid){
  // Call the views_embed_view function to returned themed view output
  $res = views_embed_view('newsfeed_comment', 'block_2', array($nid, $cid));
  // create a JSON object. The object will contain a property named “products” that will be set with the themed result of the executed view. 
  return drupal_json(array('comments' => $res, 'nid' => $nid));
  exit;
}


/**
 * Implement hook_init().
 */
function comments_ajax_init() {
  drupal_add_js(drupal_get_path('module', 'comments_ajax') . '/comments_ajax.js');
}

function comments_ajax_comment_form($form, $form_state, $nid) {
  $form = array();
  $form['comment']=array(
    '#type' => 'textfield',
    '#title' => 'Comment',
    '#size' => 20,
    '#maxlength' => 200,
    '#required' => TRUE
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#name' => 'submit' . intval($nid),
      '#value' => 'Save comment',
      );
  $form['nid'] = array(
      '#type' => 'hidden',
      '#value' => intval($nid),
      );
  return $form;
}

function comments_ajax_comment_form_submit($form, &$form_state) {
  global $user;
  $comment = array();
  $comment['nid'] = $form_state['values']['nid'];
  $comment['uid'] = $user->uid;
  $comment['comment'] = $form_state['values']['comment'];
  comment_save($comment);
}