<?php

/**
 * Implement hook_menu
 */
function comments_ajax_menu() {
  $items = array();
  $items['comments/get/%/%'] = array(
    'title' => 'Load comments',
    'page callback' => 'comments_ajax_load',
    'page arguments' => array(2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['comments/form/ajax/add'] = array(
    'page callback' => 'comments_ajax_form_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function comments_ajax_load($nid, $cid){
  // Call the views_embed_view function to returned themed view output
  $res = views_embed_view('newsfeed_comment', 'block_2', array($nid, $cid));
  // create a JSON object. The object will contain a property named “products” that will be set with the themed result of the executed view. 
  return drupal_json(array('comments' => $res, 'nid' => $nid));
  exit;
}


/**
 * Implement hook_init().
 */
function comments_ajax_init() {
  drupal_add_js(drupal_get_path('module', 'comments_ajax') . '/comments_ajax.js');
}


function comments_ajax_comment_form($form_state, $nid) {
  $form = array();
  $form['comment']=array(
    '#type' => 'textarea',
    '#title' => 'Comment',
    '#size' => 20,
    '#maxlength' => 200,
    '#required' => TRUE,
    '#default_value' => 'Reply or add a comment',
  );
  $form['nid'] = array(
      '#type' => 'hidden',
      '#value' => $nid,
      );
  $form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('comment'),
		'#submit' => array(),
		'#ahah' => array(
			'path' => 'comments/form/ajax/add',
			'wrapper' => 'divComments-' . $nid,
			'method' => 'append',
			'effect' => 'fade',
			'progress' => array('type' => 'bar', 'message' => t('Please wait...')),
		),
	);
  return $form;
}


function comments_ajax_theme() {
  return array(
    'comments_ajax_theme' => array(
      'template' => 'comments_ajax',
      'arguments' => array('user' => NULL, 'comment' => NULL, 'avatar' => NULL),
    ),
  );
}

function comments_ajax_form_callback() {
  global $user;
  $user_image_path = $user->field_user_picture[0]['filepath'];
  if (trim($user_image_path) == '') {
    $user_image_path = drupal_get_path('module', 'fb_style_dropdown').'/default.gif';
  }
  $user_image = theme('imagecache', 'newsfeeds_comment_avatar', $user_image_path);
  $avatar =  l($user_image, 'user/' . $user->uid, array('attributes' => array('target'=>"_blank"), 'html' => TRUE,));
  
  $comment = array();
  $comment['nid'] = $_REQUEST['nid'];
  $comment['uid'] = $user->uid;
  $comment['comment'] = $_REQUEST['comment'];
  $cid = comment_save($comment);
  $comment = _comment_load($cid);
  
	$output = theme('comments_ajax_theme', $user, $comment, $avatar);
  
  
	drupal_json(array('status' => TRUE, 'data' => $output));
}